image:
  name: klakegg/hugo:ext-alpine
  entrypoint: ["/bin/sh", "-c"]    # possible fix

variables:
  GIT_SUBMODULE_STRATEGY: recursive

pages:
  script:
  - hugo
  artifacts:
    paths:
    - public
  only:
  - master
